import Link from "next/link";
import { notFound } from "next/navigation";

import { getJob } from "@/lib/queries";

export const dynamic = "force-dynamic";

const ATS_LABEL: Record<string, string> = {
  greenhouse: "Greenhouse",
  ashby: "Ashby",
  lever: "Lever",
  smartrecruiters: "SmartRecruiters",
  workday: "Workday",
};

// PageProps<'/jobs/[id]'> is generated by `next typegen`; params/searchParams
// are Promises in Next.js 16 and must be awaited.
export default async function JobPage(props: PageProps<'/jobs/[id]'>) {
  const { id } = await props.params;
  const job = await getJob(id);
  if (!job) notFound();

  return (
    <main className="mx-auto max-w-3xl px-4 py-8">
      <Link href="/" className="text-sm text-neutral-500 hover:underline">
        ← All jobs
      </Link>

      <header className="mt-4 border-b border-neutral-200 pb-5 dark:border-neutral-800">
        <h1 className="text-2xl font-semibold tracking-tight">{job.title}</h1>
        <p className="mt-2 text-neutral-600 dark:text-neutral-400">
          <span className="font-medium">{job.company_name}</span>
          {job.location_raw && <> · {job.location_raw}</>}
          {job.department && <> · {job.department}</>}
        </p>

        {job.closed_at && (
          <p className="mt-3 rounded-md bg-amber-50 px-3 py-2 text-sm text-amber-800 dark:bg-amber-950 dark:text-amber-200">
            This role no longer appears on the company&apos;s board — it was probably filled or withdrawn.
          </p>
        )}

        <div className="mt-4 flex flex-wrap items-center gap-3">
          <a
            href={job.apply_url}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-md bg-neutral-900 px-4 py-2 text-sm font-medium text-white hover:bg-neutral-700 dark:bg-white dark:text-neutral-900 dark:hover:bg-neutral-200"
          >
            Apply on {ATS_LABEL[job.ats] ?? job.ats} ↗
          </a>
          {job.posted_at && (
            <span className="text-sm text-neutral-500">
              Posted {new Date(job.posted_at).toLocaleDateString()}
            </span>
          )}
        </div>
      </header>

      {job.description_html ? (
        // Already sanitized with nh3 server-side during ingestion; do not
        // re-sanitize here.
        <article
          className="prose prose-neutral mt-6 max-w-none text-[0.95rem] leading-relaxed dark:prose-invert prose-headings:text-base prose-headings:font-semibold prose-a:underline"
          dangerouslySetInnerHTML={{ __html: job.description_html }}
        />
      ) : (
        <p className="mt-8 text-sm text-neutral-500">
          No description stored yet — open the original posting to read it.
        </p>
      )}
    </main>
  );
}
