import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import LiveCheck from "@/components/LiveCheck";
import { Tag, payLabel, remoteLabel } from "@/components/Tags";
import { expLabel } from "@/lib/experience";
import { getJob, sameRole } from "@/lib/queries";
import { countryLanding, jobPostingData, jsonLd } from "@/lib/seo";

export const dynamic = "force-dynamic";

const ATS_LABEL: Record<string, string> = {
  greenhouse: "Greenhouse",
  ashby: "Ashby",
  lever: "Lever",
  smartrecruiters: "SmartRecruiters",
  workday: "Workday",
};

export async function generateMetadata(props: PageProps<'/jobs/[id]'>): Promise<Metadata> {
  const job = await getJob((await props.params).id);
  if (!job) return {};
  // "Linear · Remote, anywhere · $160K–$200K · Posted 3 Oct 2026. Apply on the
  // company's own careers page." Unique per job, which is what search results show.
  // Remote: where from ("Remote · anywhere"), which says more than the
  // location line, often just "Remote" again.
  const where = remoteLabel(job)?.text ?? [job.location_raw, job.remote_scope === "hybrid" && "Hybrid"].filter(Boolean).join(", ");
  const posted = job.posted_at ?? job.first_seen_at;
  const description = [
    job.company_name,
    where,
    payLabel(job),
    expLabel(job.exp_min_years, job.exp_max_years),
    posted && `Posted ${shortDate(posted)}`,
  ]
    .filter(Boolean)
    .join(" · ");
  const title = `${job.title} at ${job.company_name}`;
  return {
    title,
    description: `${description}. Apply on the employer's own careers page.`,
    alternates: { canonical: `/jobs/${job.id}` },
    // A closed role stays reachable from old links but leaves search results.
    ...(job.closed_at && { robots: { index: false } }),
    openGraph: { title, description, type: "website" },
  };
}

const DAY = 86_400_000;

function shortDate(iso: string, withTime = false): string {
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric",
    month: "short",
    ...(withTime ? { hour: "2-digit", minute: "2-digit", timeZone: "UTC", timeZoneName: "short" } : { year: "numeric" }),
  });
}

/**
 * The employer's posted date is what the ATS says; "first seen" is when Unlisted
 * found it. Claims about the gap need evidence, because a pause in syncing would
 * also make a job look late:
 *
 * - found on the board's first sync: it was simply already there;
 * - the board was checked after the posted date and the job wasn't on it: it
 *   appeared later than its date says (a repost or backdated listing);
 * - otherwise: just say when it was first seen.
 */
function firstSeenNote(job: {
  posted_at: string | null;
  first_seen_at?: string | null;
  first_synced_at?: string | null;
  board_checked_before?: string | null;
}) {
  const { posted_at, first_seen_at, first_synced_at, board_checked_before } = job;
  if (!first_seen_at) return null;
  const seen = new Date(first_seen_at).getTime();
  if (first_synced_at && seen < new Date(first_synced_at).getTime() + 2 * 3_600_000) {
    return `Already listed when Unlisted started watching this board (${shortDate(first_synced_at)})`;
  }
  if (posted_at && board_checked_before) {
    const posted = new Date(posted_at).getTime();
    const checked = new Date(board_checked_before).getTime();
    if (checked - posted >= DAY) {
      return `First seen by Unlisted ${shortDate(first_seen_at, true)}. It wasn't on the board at the check on ${shortDate(board_checked_before, true)}, after its posted date, so it may be a repost.`;
    }
  }
  return `First seen by Unlisted ${shortDate(first_seen_at, true)}`;
}

function Fact({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-4 py-2.5 sm:block sm:py-0">
      <dt className="w-28 shrink-0 font-mono text-xs uppercase tracking-[0.06em] text-muted sm:w-auto">{label}</dt>
      <dd className="min-w-0 text-sm text-ink-strong sm:mt-1">{children}</dd>
    </div>
  );
}

// PageProps<'/jobs/[id]'> is generated by `next typegen`; params/searchParams
// are Promises in Next.js 16 and must be awaited.
export default async function JobPage(props: PageProps<'/jobs/[id]'>) {
  const { id } = await props.params;
  const [job, others] = await Promise.all([getJob(id), sameRole(id)]);
  if (!job) notFound();

  const remote = remoteLabel(job);
  const exp = expLabel(job.exp_min_years, job.exp_max_years);
  const ats = ATS_LABEL[job.ats] ?? job.ats;
  const pay = payLabel(job);
  const posting = jobPostingData(job);

  return (
    <main id="main" className="mx-auto w-full min-w-0 max-w-3xl px-4 pb-16 pt-8 sm:pt-12">
      {posting && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(posting) }} />}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-muted transition-colors hover:text-ink-strong"
      >
        <span aria-hidden>←</span> All jobs
      </Link>

      <header className="mt-6">
        <p className="text-sm text-ink">
          {job.company_slug ? (
            <Link
              href={`/companies/${job.company_slug}`}
              className="underline decoration-line underline-offset-4 transition-colors hover:decoration-current"
              title={`Every open role at ${job.company_name}`}
            >
              {job.company_name}
            </Link>
          ) : (
            job.company_name
          )}
          {job.department && <span className="text-muted"> · {job.department}</span>}
        </p>
        <h1 className="mt-1 text-balance font-serif text-4xl leading-[1.08] tracking-[-0.02em] text-ink-strong sm:text-5xl">
          {job.title}
        </h1>

        {job.closed_at && (
          <p className="mt-5 rounded-md bg-yellow-bg px-3 py-2.5 text-sm text-yellow-ink">
            This role is no longer on the company&apos;s board, so it was probably filled or withdrawn.
          </p>
        )}

        <dl className="mt-8 grid divide-y divide-line border-y border-line sm:grid-cols-4 sm:gap-6 sm:divide-y-0 sm:py-5">
          <Fact label="Where">
            <span className="block">{job.location_raw ?? "Not stated"}</span>
            {(remote || job.remote_scope === "hybrid") && (
              <span className="mt-1.5 flex flex-wrap gap-1.5">
                {remote && <Tag tone={remote.tone} title={remote.title}>{remote.text}</Tag>}
                {job.remote_scope === "hybrid" && <Tag>Hybrid</Tag>}
              </span>
            )}
          </Fact>
          <Fact label="Experience">
            {exp ? (
              <>
                <span className="font-mono tabular-nums">{exp}</span>
                <span className="block text-xs text-muted">
                  {job.exp_source === "title" ? "guessed from the title" : "stated in the description"}
                </span>
              </>
            ) : (
              <span className="text-muted">Not stated</span>
            )}
          </Fact>
          <Fact label="Pay">
            {pay ? (
              <>
                <span className="font-mono tabular-nums">{pay}</span>
                <span className="block text-xs text-muted">base, as stated on the posting</span>
              </>
            ) : (
              <span className="text-muted">Not stated</span>
            )}
          </Fact>
          <Fact label="Posted">
            {job.posted_at ? (
              <time dateTime={job.posted_at} className="font-mono tabular-nums" title="The date on the employer's posting">
                {shortDate(job.posted_at)}
              </time>
            ) : (
              <span className="text-muted">Unknown</span>
            )}
            {firstSeenNote(job) && <span className="mt-0.5 block text-xs text-muted">{firstSeenNote(job)}</span>}
          </Fact>
        </dl>

        <div className="mt-6 flex flex-wrap items-center gap-x-4 gap-y-2">
          <a
            href={job.apply_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-md bg-ink-strong px-5 py-2.5 text-sm font-medium text-canvas transition-[opacity,transform] duration-200 hover:opacity-85 active:scale-[0.98]"
          >
            Apply on {ats}
            <svg aria-hidden viewBox="0 0 16 16" className="size-3.5">
              <path d="M5 11l6-6M6 5h5v5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </a>
          <span className="text-xs text-muted">Opens the employer&apos;s own posting</span>
        </div>
        {!job.closed_at && (
          <div className="mt-3">
            <LiveCheck jobId={job.id} ats={ats} />
          </div>
        )}
      </header>

      {others.length > 0 && (
        <details className="mt-10 border-y border-line py-4">
          <summary className="cursor-pointer text-sm text-ink-strong">
            {others.length} other {others.length === 1 ? "posting" : "postings"} of this role
          </summary>
          <ul className="mt-3 grid gap-x-6 gap-y-1.5 text-sm sm:grid-cols-2">
            {others.map((o) => (
              <li key={o.id} className="min-w-0">
                <Link
                  href={`/jobs/${o.id}`}
                  className="text-ink underline decoration-line underline-offset-4 transition-colors [overflow-wrap:anywhere] hover:text-ink-strong hover:decoration-current"
                >
                  {o.location_raw ?? "Location not stated"}
                </Link>
              </li>
            ))}
          </ul>
        </details>
      )}

      {job.description_html ? (
        // Already sanitized with nh3 server-side during ingestion; do not
        // re-sanitize here.
        <article
          className="prose prose-job mt-12 max-w-[68ch] text-[15px] leading-[1.7] [overflow-wrap:anywhere] prose-headings:text-base prose-headings:font-semibold prose-a:underline-offset-4"
          dangerouslySetInnerHTML={{ __html: job.description_html }}
        />
      ) : (
        <p className="mt-12 text-sm text-muted">
          No description stored. Open the original posting to read it.
        </p>
      )}

      {/* More like this: the pages search engines (and people) move on to. */}
      <nav aria-label="More roles" className="mt-14 flex flex-wrap gap-x-5 gap-y-2 border-t border-line pt-6 text-sm">
        {job.company_slug && (
          <Link href={`/companies/${job.company_slug}`} className="text-ink underline decoration-line underline-offset-4 hover:text-ink-strong">
            All roles at {job.company_name}
          </Link>
        )}
        {job.country && (
          <Link href={countryLanding(job.country).path} className="text-ink underline decoration-line underline-offset-4 hover:text-ink-strong">
            {countryLanding(job.country).title}
          </Link>
        )}
        {job.remote && (
          <Link href="/remote" className="text-ink underline decoration-line underline-offset-4 hover:text-ink-strong">
            Remote jobs
          </Link>
        )}
      </nav>
    </main>
  );
}
