import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Tag, remoteLabel } from "@/components/Tags";
import { expLabel } from "@/lib/experience";
import { getJob } from "@/lib/queries";

export const dynamic = "force-dynamic";

const ATS_LABEL: Record<string, string> = {
  greenhouse: "Greenhouse",
  ashby: "Ashby",
  lever: "Lever",
  smartrecruiters: "SmartRecruiters",
  workday: "Workday",
};

export async function generateMetadata(props: PageProps<'/jobs/[id]'>): Promise<Metadata> {
  const job = await getJob((await props.params).id);
  return job ? { title: `${job.title} at ${job.company_name}` } : {};
}

function Fact({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-4 py-2.5 sm:block sm:py-0">
      <dt className="w-28 shrink-0 font-mono text-xs uppercase tracking-[0.06em] text-muted sm:w-auto">{label}</dt>
      <dd className="min-w-0 text-sm text-ink-strong sm:mt-1">{children}</dd>
    </div>
  );
}

// PageProps<'/jobs/[id]'> is generated by `next typegen`; params/searchParams
// are Promises in Next.js 16 and must be awaited.
export default async function JobPage(props: PageProps<'/jobs/[id]'>) {
  const { id } = await props.params;
  const job = await getJob(id);
  if (!job) notFound();

  const remote = remoteLabel(job);
  const exp = expLabel(job.exp_min_years, job.exp_max_years);
  const ats = ATS_LABEL[job.ats] ?? job.ats;

  return (
    <main id="main" className="mx-auto w-full min-w-0 max-w-3xl px-4 pb-16 pt-8 sm:pt-12">
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-muted transition-colors hover:text-ink-strong"
      >
        <span aria-hidden>←</span> All jobs
      </Link>

      <header className="mt-6">
        <p className="text-sm text-ink">
          {job.company_name}
          {job.department && <span className="text-muted"> · {job.department}</span>}
        </p>
        <h1 className="mt-1 text-balance font-serif text-4xl leading-[1.08] tracking-[-0.02em] text-ink-strong sm:text-5xl">
          {job.title}
        </h1>

        {job.closed_at && (
          <p className="mt-5 rounded-md bg-yellow-bg px-3 py-2.5 text-sm text-yellow-ink">
            This role is no longer on the company&apos;s board, so it was probably filled or withdrawn.
          </p>
        )}

        <dl className="mt-8 grid divide-y divide-line border-y border-line sm:grid-cols-3 sm:gap-6 sm:divide-y-0 sm:py-5">
          <Fact label="Where">
            <span className="block">{job.location_raw ?? "Not stated"}</span>
            {(remote || job.remote_scope === "hybrid") && (
              <span className="mt-1.5 flex flex-wrap gap-1.5">
                {remote && <Tag tone={remote.tone} title={remote.title}>{remote.text}</Tag>}
                {job.remote_scope === "hybrid" && <Tag>Hybrid</Tag>}
              </span>
            )}
          </Fact>
          <Fact label="Experience">
            {exp ? (
              <>
                <span className="font-mono tabular-nums">{exp}</span>
                <span className="block text-xs text-muted">
                  {job.exp_source === "title" ? "guessed from the title" : "stated in the description"}
                </span>
              </>
            ) : (
              <span className="text-muted">Not stated</span>
            )}
          </Fact>
          <Fact label="Posted">
            {job.posted_at ? (
              <time dateTime={job.posted_at} className="font-mono tabular-nums">
                {new Date(job.posted_at).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
              </time>
            ) : (
              <span className="text-muted">Unknown</span>
            )}
          </Fact>
        </dl>

        <div className="mt-6 flex flex-wrap items-center gap-x-4 gap-y-2">
          <a
            href={job.apply_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-md bg-ink-strong px-5 py-2.5 text-sm font-medium text-canvas transition-[opacity,transform] duration-200 hover:opacity-85 active:scale-[0.98]"
          >
            Apply on {ats}
            <svg aria-hidden viewBox="0 0 16 16" className="size-3.5">
              <path d="M5 11l6-6M6 5h5v5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </a>
          <span className="text-xs text-muted">Opens the employer&apos;s own posting</span>
        </div>
      </header>

      {job.description_html ? (
        // Already sanitized with nh3 server-side during ingestion; do not
        // re-sanitize here.
        <article
          className="prose prose-job mt-12 max-w-[68ch] text-[15px] leading-[1.7] [overflow-wrap:anywhere] prose-headings:text-base prose-headings:font-semibold prose-a:underline-offset-4"
          dangerouslySetInnerHTML={{ __html: job.description_html }}
        />
      ) : (
        <p className="mt-12 text-sm text-muted">
          No description stored. Open the original posting to read it.
        </p>
      )}
    </main>
  );
}
